create database salesdb;
use salesdb;

create table salesdb.brands(brand_id int primary key,brand_name varchar(70));

create table salesdb.categories (Category_id int primary key, category_name varchar(70));

create table salesdb.customers (customer_id int primary key, First_name varchar(100), Last_name varchar(100), Email varchar(100),
 street varchar(100), city varchar(100), state varchar(100), zip_code int);
 
 create table salesdb.order_items (order_id int,item_id int, product_id int, quantity int,list_price double, discount double, total_price double);

create table salesdb.orders (order_id int Primary key, customer_id int, order_status text, order_date text, required_date text, shipped_date text, store_id int, staff_id int);

create table salesdb.products (Product_id int Primary key, Product_name varchar(100), Brand_id int,Category_id int, model_year int, List_price double);

create table salesdb.staffs (Staff_id int Primary key, first_name varchar(100), last_name varchar(100), Email varchar(100),phone varchar(100), active int, Store_id int, manager_id varchar(100));

create table salesdb.stocks (Store_id int, Product_id int, Quantity int);

create table salesdb.stores (Store_id int primary key, store_name varchar(100), phone varchar(100), Email varchar(100),street varchar(100), City varchar(100), state varchar(100), Zip_code int);

#Inner Join for Order Details 
-- Join orders, order_items, and products to display detailed line items. 
select * from salesdb.orders as o
inner join salesdb.order_items as oi
on o.order_id = oi.order_id
inner join salesdb.products as p
on p.product_id = oi.product_id;

#Total Sales by Store 
-- Write a query to group sales (total_price) by each store_id. 
select o.store_id,sum(oi.total_price) as total_sales from salesdb.orders as o
inner join salesdb.order_items as oi
on o.order_id = oi.order_id
group by o.store_id;

select * from salesdb.order_items;

# Top 5 Selling Products
-- Use ORDER BY and LIMIT to get the top 5 most sold products by quantity. 
select products.product_name, sum(order_items.quantity) as total_quantity
from salesdb.order_items as order_items
inner join salesdb.products as products on order_items.product_id = products.product_id
group by  products.product_name
order by total_quantity desc
limit 5;

# Customer Purchase Summary 
-- For each customer, return total orders placed, total items purchased,and total revenue.
select o.customer_id,count(distinct o.order_id) as total_orders,sum(oi.quantity) as total_items_purchased,
sum(oi.total_price) as total_revenue from salesdb.orders as o
left join salesdb.order_items as oi
on oi.order_id = o.order_id
group by o.customer_id
order by total_revenue desc;

# Segment Customers by Total Spend
-- Write a query to classify customers into spending brackets (e.g., low,medium, high). 
select c.customer_id,concat(c.first_name, ' ', c.last_name) as customer_name,sum(oi.total_price) as total_spending,
case
when sum(oi.Total_price) < 10000 then 'Low'
when sum(oi.Total_price) < 50000 then 'Medium'
else 'High'
end as spending_segment
from salesdb.customers as c
join salesdb.orders as o
on c.customer_id = o.customer_id
join salesdb.order_items as oi
on o.order_id = oi.order_id
group by c.customer_id,c.first_name,c.last_name;



#Staff Performance Analysis
-- Analyze total revenue generated by each staff member based on their handled orders.
select s.staff_id,concat(s.first_name, ' ', s.last_name) as staff_name,sum(oi.total_price) as total_revenue
from salesdb.staffs as s
join salesdb.orders as o
on s.staff_id = o.staff_id
join salesdb.order_items oi
on o.order_id = oi.order_id
group by s.staff_id,s.first_name,s.last_name
order by total_revenue DESC;



#Stock Alert Query 
-- Write a query to list products where stock quantity < 10 in any store.
select s.store_id,s.product_id,p.product_name,s.quantity as stock_quantity
from salesdb.stocks as s
join salesdb.products as p
on s.product_id = p.product_id
where s.quantity < 10;


-- 10 ) 

SELECT *
FROM salesdb.customer_segments
LIMIT 10;


